//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation_Framework.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automation_Framework.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual (1st Party).
        /// </summary>
        internal static string Actual1st {
            get {
                return ResourceManager.GetString("Actual1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual (3rd Party).
        /// </summary>
        internal static string Actual3rd {
            get {
                return ResourceManager.GetString("Actual3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertorial/Email.
        /// </summary>
        internal static string AdvertorialEmail {
            get {
                return ResourceManager.GetString("AdvertorialEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Fee.
        /// </summary>
        internal static string AgencyFee {
            get {
                return ResourceManager.GetString("AgencyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Cost.
        /// </summary>
        internal static string BaseCost {
            get {
                return ResourceManager.GetString("BaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Source.
        /// </summary>
        internal static string BillingSource {
            get {
                return ResourceManager.GetString("BillingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefs and Proposals.
        /// </summary>
        internal static string BriefsAndProposals {
            get {
                return ResourceManager.GetString("BriefsAndProposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email delivery succeeded.
        /// </summary>
        internal static string BriefSentSuccess {
            get {
                return ResourceManager.GetString("BriefSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifications.
        /// </summary>
        internal static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Cost %.
        /// </summary>
        internal static string ClientCost {
            get {
                return ResourceManager.GetString("ClientCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Media Schedule.
        /// </summary>
        internal static string ConfirmMediaSchedule {
            get {
                return ResourceManager.GetString("ConfirmMediaSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Basis.
        /// </summary>
        internal static string CostBasis {
            get {
                return ResourceManager.GetString("CostBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPM.
        /// </summary>
        internal static string CPM {
            get {
                return ResourceManager.GetString("CPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Campaign.
        /// </summary>
        internal static string CreateCampaign {
            get {
                return ResourceManager.GetString("CreateCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateIOLnkTxt {
            get {
                return ResourceManager.GetString("CreateIOLnkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Type.
        /// </summary>
        internal static string CreativeType {
            get {
                return ResourceManager.GetString("CreativeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy}.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 1.
        /// </summary>
        internal static string Discount1 {
            get {
                return ResourceManager.GetString("Discount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 2.
        /// </summary>
        internal static string Discount2 {
            get {
                return ResourceManager.GetString("Discount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 3.
        /// </summary>
        internal static string Discount3 {
            get {
                return ResourceManager.GetString("Discount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 4.
        /// </summary>
        internal static string Discount4 {
            get {
                return ResourceManager.GetString("Discount4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 5.
        /// </summary>
        internal static string Discount5 {
            get {
                return ResourceManager.GetString("Discount5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 6.
        /// </summary>
        internal static string Discount6 {
            get {
                return ResourceManager.GetString("Discount6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal (Impressions).
        /// </summary>
        internal static string GoalImpressions {
            get {
                return ResourceManager.GetString("GoalImpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal (Optional).
        /// </summary>
        internal static string GoalOptional {
            get {
                return ResourceManager.GetString("GoalOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedule item(s) have been successfully imported.
        /// </summary>
        internal static string ImportSuccessMessage {
            get {
                return ResourceManager.GetString("ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IO has been successfully signed off.
        /// </summary>
        internal static string IOSignedOffSuccess {
            get {
                return ResourceManager.GetString("IOSignedOffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string L2NavigationBillingTxt {
            get {
                return ResourceManager.GetString("L2NavigationBillingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefs and Proposals.
        /// </summary>
        internal static string L2NavigationBriefsProposalsTxt {
            get {
                return ResourceManager.GetString("L2NavigationBriefsProposalsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string L2NavigationCampaignDetailsTxt {
            get {
                return ResourceManager.GetString("L2NavigationCampaignDetailsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Campaign.
        /// </summary>
        internal static string L2NavigationCreateCampaignTxt {
            get {
                return ResourceManager.GetString("L2NavigationCreateCampaignTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion Order.
        /// </summary>
        internal static string L2NavigationInsertionOrderTxt {
            get {
                return ResourceManager.GetString("L2NavigationInsertionOrderTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        internal static string L2NavigationMarketplaceTxt {
            get {
                return ResourceManager.GetString("L2NavigationMarketplaceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Schedule.
        /// </summary>
        internal static string L2NavigationMediaScheduleTxt {
            get {
                return ResourceManager.GetString("L2NavigationMediaScheduleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string L2NavigationReportsTxt {
            get {
                return ResourceManager.GetString("L2NavigationReportsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        internal static string L2NavigationTrafficTxt {
            get {
                return ResourceManager.GetString("L2NavigationTrafficTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing page.
        /// </summary>
        internal static string LandingPage {
            get {
                return ResourceManager.GetString("LandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line items were successfully confirmed.
        /// </summary>
        internal static string LineItemsSuccessfullyConfirmedMsg {
            get {
                return ResourceManager.GetString("LineItemsSuccessfullyConfirmedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line item updated successfully.
        /// </summary>
        internal static string LineUpdateSuccess {
            get {
                return ResourceManager.GetString("LineUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        internal static string Marketplace {
            get {
                return ResourceManager.GetString("Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Schedule.
        /// </summary>
        internal static string MediaSchedule {
            get {
                return ResourceManager.GetString("MediaSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule item was successfully added.
        /// </summary>
        internal static string MediaScheduleItemAddSuccess {
            get {
                return ResourceManager.GetString("MediaScheduleItemAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cost.
        /// </summary>
        internal static string NetCost {
            get {
                return ResourceManager.GetString("NetCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cost incl Prepay.
        /// </summary>
        internal static string NetCostInclPrepay {
            get {
                return ResourceManager.GetString("NetCostInclPrepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to display..
        /// </summary>
        internal static string NoItemsToDisplayMsg {
            get {
                return ResourceManager.GetString("NoItemsToDisplayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered.
        /// </summary>
        internal static string Ordered {
            get {
                return ResourceManager.GetString("Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cost item has been successfully created.
        /// </summary>
        internal static string OtherCostItemCreatedSuccess {
            get {
                return ResourceManager.GetString("OtherCostItemCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package was successfully created.
        /// </summary>
        internal static string PackageCreatedSuccess {
            get {
                return ResourceManager.GetString("PackageCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Done! Performance Package has been added to media schedule..
        /// </summary>
        internal static string PerformanceAddSuccess {
            get {
                return ResourceManager.GetString("PerformanceAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Done! Placement has been added to media schedule..
        /// </summary>
        internal static string PlacementAddSuccess {
            get {
                return ResourceManager.GetString("PlacementAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay Discount.
        /// </summary>
        internal static string PrepayDiscount {
            get {
                return ResourceManager.GetString("PrepayDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items successfully imported.
        /// </summary>
        internal static string ProposalItemsImportSuccess {
            get {
                return ResourceManager.GetString("ProposalItemsImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Cost.
        /// </summary>
        internal static string PurchaseCost {
            get {
                return ResourceManager.GetString("PurchaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Type.
        /// </summary>
        internal static string PurchaseType {
            get {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratecard.
        /// </summary>
        internal static string Ratecard {
            get {
                return ResourceManager.GetString("Ratecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Keyword.
        /// </summary>
        internal static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowDiscountsLnkTxt {
            get {
                return ResourceManager.GetString("ShowDiscountsLnkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Display.
        /// </summary>
        internal static string StandardDisplay {
            get {
                return ResourceManager.GetString("StandardDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost (Others).
        /// </summary>
        internal static string TotalOtherCost {
            get {
                return ResourceManager.GetString("TotalOtherCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trafficking is currently underway for this campaign. Please try again later..
        /// </summary>
        internal static string TraffickingUnderwayMsg {
            get {
                return ResourceManager.GetString("TraffickingUnderwayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Commission.
        /// </summary>
        internal static string VendorCommission {
            get {
                return ResourceManager.GetString("VendorCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
